general.import = ["~/.cache/wal/colors-alacritty.toml"]
general.live_config_reload = true

[window]
decorations = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true

[font]
size = 13
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }

[cursor]
style = { shape = "Beam", blinking = "On" }

[keyboard]
bindings = [
  { key = "V", mods = "Control", mode = "~Vi", action = "Paste" },
  { key = "C", mods = "Control", action = "Copy"                },
]
